/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatV4FriendrequestsPost200Response {
    /// Empty array
    #[serde(rename = "requests")]
    pub requests: Vec<serde_json::Value>,
}

impl ChatV4FriendrequestsPost200Response {
    pub fn new(requests: Vec<serde_json::Value>) -> ChatV4FriendrequestsPost200Response {
        ChatV4FriendrequestsPost200Response {
            requests,
        }
    }
}

