/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatV4PresencesGet200Response {
    #[serde(rename = "presences")]
    pub presences: Vec<models::ChatV4PresencesGet200ResponsePresencesInner>,
}

impl ChatV4PresencesGet200Response {
    pub fn new(presences: Vec<models::ChatV4PresencesGet200ResponsePresencesInner>) -> ChatV4PresencesGet200Response {
        ChatV4PresencesGet200Response {
            presences,
        }
    }
}

