/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatV4FriendsGet200Response {
    #[serde(rename = "friends")]
    pub friends: Vec<models::ChatV4FriendsGet200ResponseFriendsInner>,
}

impl ChatV4FriendsGet200Response {
    pub fn new(friends: Vec<models::ChatV4FriendsGet200ResponseFriendsInner>) -> ChatV4FriendsGet200Response {
        ChatV4FriendsGet200Response {
            friends,
        }
    }
}

