/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatV5ParticipantsGet200Response {
    #[serde(rename = "participants")]
    pub participants: Vec<models::ChatV5ParticipantsGet200ResponseParticipantsInner>,
}

impl ChatV5ParticipantsGet200Response {
    pub fn new(participants: Vec<models::ChatV5ParticipantsGet200ResponseParticipantsInner>) -> ChatV5ParticipantsGet200Response {
        ChatV5ParticipantsGet200Response {
            participants,
        }
    }
}

