/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatV6ConversationsAresPartiesGet200ResponseConversationsInnerUiState {
    #[serde(rename = "changedSinceHidden")]
    pub changed_since_hidden: bool,
    #[serde(rename = "hidden")]
    pub hidden: bool,
}

impl ChatV6ConversationsAresPartiesGet200ResponseConversationsInnerUiState {
    pub fn new(
        changed_since_hidden: bool,
        hidden: bool,
    ) -> ChatV6ConversationsAresPartiesGet200ResponseConversationsInnerUiState {
        ChatV6ConversationsAresPartiesGet200ResponseConversationsInnerUiState {
            changed_since_hidden,
            hidden,
        }
    }
}
