/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatV6MessagesGet200Response {
    #[serde(rename = "messages")]
    pub messages: Vec<models::ChatV6MessagesGet200ResponseMessagesInner>,
}

impl ChatV6MessagesGet200Response {
    pub fn new(messages: Vec<models::ChatV6MessagesGet200ResponseMessagesInner>) -> ChatV6MessagesGet200Response {
        ChatV6MessagesGet200Response {
            messages,
        }
    }
}

