/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PlayerAccountAliasesV1ActiveGet200Response {
    #[serde(rename = "active")]
    pub active: bool,
    /// Milliseconds since epoch
    #[serde(rename = "created_datetime")]
    pub created_datetime: f64,
    #[serde(rename = "game_name")]
    pub game_name: String,
    #[serde(rename = "summoner")]
    pub summoner: bool,
    #[serde(rename = "tag_line")]
    pub tag_line: String,
}

impl PlayerAccountAliasesV1ActiveGet200Response {
    pub fn new(active: bool, created_datetime: f64, game_name: String, summoner: bool, tag_line: String) -> PlayerAccountAliasesV1ActiveGet200Response {
        PlayerAccountAliasesV1ActiveGet200Response {
            active,
            created_datetime,
            game_name,
            summoner,
            tag_line,
        }
    }
}

