/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RiotclientRegionLocaleGet200Response {
    #[serde(rename = "locale")]
    pub locale: String,
    #[serde(rename = "region")]
    pub region: String,
    #[serde(rename = "webLanguage")]
    pub web_language: String,
    #[serde(rename = "webRegion")]
    pub web_region: String,
}

impl RiotclientRegionLocaleGet200Response {
    pub fn new(locale: String, region: String, web_language: String, web_region: String) -> RiotclientRegionLocaleGet200Response {
        RiotclientRegionLocaleGet200Response {
            locale,
            region,
            web_language,
            web_region,
        }
    }
}

