/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthRiotgamesComApiV1AuthorizationPut200Response {
    #[serde(rename = "hoge")]
    pub hoge: f64,
}

impl AuthRiotgamesComApiV1AuthorizationPut200Response {
    pub fn new(hoge: f64) -> AuthRiotgamesComApiV1AuthorizationPut200Response {
        AuthRiotgamesComApiV1AuthorizationPut200Response { hoge }
    }
}
