/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthRiotgamesComUserinfoGet200ResponseAcct {
    #[serde(rename = "type")]
    pub r#type: f64,
    #[serde(rename = "state")]
    pub state: String,
    #[serde(rename = "adm")]
    pub adm: bool,
    #[serde(rename = "game_name")]
    pub game_name: String,
    #[serde(rename = "tag_line")]
    pub tag_line: String,
    /// Milliseconds since epoch
    #[serde(rename = "created_at")]
    pub created_at: f64,
}

impl AuthRiotgamesComUserinfoGet200ResponseAcct {
    pub fn new(r#type: f64, state: String, adm: bool, game_name: String, tag_line: String, created_at: f64) -> AuthRiotgamesComUserinfoGet200ResponseAcct {
        AuthRiotgamesComUserinfoGet200ResponseAcct {
            r#type,
            state,
            adm,
            game_name,
            tag_line,
            created_at,
        }
    }
}

