/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthRiotgamesComUserinfoGet200ResponsePw {
    /// Milliseconds since epoch
    #[serde(rename = "cng_at")]
    pub cng_at: f64,
    #[serde(rename = "reset")]
    pub reset: bool,
    #[serde(rename = "must_reset")]
    pub must_reset: bool,
}

impl AuthRiotgamesComUserinfoGet200ResponsePw {
    pub fn new(cng_at: f64, reset: bool, must_reset: bool) -> AuthRiotgamesComUserinfoGet200ResponsePw {
        AuthRiotgamesComUserinfoGet200ResponsePw {
            cng_at,
            reset,
            must_reset,
        }
    }
}

