/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RiotGeoPasSiRiotgamesComPasV1ProductValorantPut200Response {
    #[serde(rename = "token")]
    pub token: String,
    #[serde(rename = "affinities")]
    pub affinities:
        Box<models::RiotGeoPasSiRiotgamesComPasV1ProductValorantPut200ResponseAffinities>,
}

impl RiotGeoPasSiRiotgamesComPasV1ProductValorantPut200Response {
    pub fn new(
        token: String,
        affinities: models::RiotGeoPasSiRiotgamesComPasV1ProductValorantPut200ResponseAffinities,
    ) -> RiotGeoPasSiRiotgamesComPasV1ProductValorantPut200Response {
        RiotGeoPasSiRiotgamesComPasV1ProductValorantPut200Response {
            token,
            affinities: Box::new(affinities),
        }
    }
}
