/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountXpV1PlayersPuuidGet200ResponseHistoryInnerXpSourcesInner {
    #[serde(rename = "ID")]
    pub id: Id,
    #[serde(rename = "Amount")]
    pub amount: f64,
}

impl AccountXpV1PlayersPuuidGet200ResponseHistoryInnerXpSourcesInner {
    pub fn new(id: Id, amount: f64) -> AccountXpV1PlayersPuuidGet200ResponseHistoryInnerXpSourcesInner {
        AccountXpV1PlayersPuuidGet200ResponseHistoryInnerXpSourcesInner {
            id,
            amount,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Id {
    #[serde(rename = "time-played")]
    TimePlayed,
    #[serde(rename = "match-win")]
    MatchWin,
    #[serde(rename = "first-win-of-the-day")]
    FirstWinOfTheDay,
}

impl Default for Id {
    fn default() -> Id {
        Self::TimePlayed
    }
}

