/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountXpV1PlayersPuuidGet200ResponseProgress {
    #[serde(rename = "Level")]
    pub level: f64,
    #[serde(rename = "XP")]
    pub xp: f64,
}

impl AccountXpV1PlayersPuuidGet200ResponseProgress {
    pub fn new(level: f64, xp: f64) -> AccountXpV1PlayersPuuidGet200ResponseProgress {
        AccountXpV1PlayersPuuidGet200ResponseProgress {
            level,
            xp,
        }
    }
}

