/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContractsV1ContractsPuuidGet200ResponseProcessedMatchesInnerContractDeltasValue {
    /// UUID
    #[serde(rename = "ID")]
    pub id: String,
    #[serde(rename = "TotalXPBefore")]
    pub total_xp_before: f64,
    #[serde(rename = "TotalXPAfter")]
    pub total_xp_after: f64,
}

impl ContractsV1ContractsPuuidGet200ResponseProcessedMatchesInnerContractDeltasValue {
    pub fn new(id: String, total_xp_before: f64, total_xp_after: f64) -> ContractsV1ContractsPuuidGet200ResponseProcessedMatchesInnerContractDeltasValue {
        ContractsV1ContractsPuuidGet200ResponseProcessedMatchesInnerContractDeltasValue {
            id,
            total_xp_before,
            total_xp_after,
        }
    }
}

