/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContractDefinitionsV3ItemUpgradesGet200Response {
    #[serde(rename = "Definitions")]
    pub definitions: Vec<models::ContractDefinitionsV3ItemUpgradesGet200ResponseDefinitionsInner>,
}

impl ContractDefinitionsV3ItemUpgradesGet200Response {
    pub fn new(definitions: Vec<models::ContractDefinitionsV3ItemUpgradesGet200ResponseDefinitionsInner>) -> ContractDefinitionsV3ItemUpgradesGet200Response {
        ContractDefinitionsV3ItemUpgradesGet200Response {
            definitions,
        }
    }
}

