/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContractsV1ContractsPuuidGet200ResponseProcessedMatchesInnerXpGrantsModifier {
    #[serde(rename = "Value")]
    pub value: f64,
    #[serde(rename = "BaseMultiplierValue")]
    pub base_multiplier_value: f64,
    #[serde(rename = "Modifiers")]
    pub modifiers: Vec<models::ContractsV1ContractsPuuidGet200ResponseProcessedMatchesInnerXpGrantsModifierModifiersInner>,
}

impl ContractsV1ContractsPuuidGet200ResponseProcessedMatchesInnerXpGrantsModifier {
    pub fn new(value: f64, base_multiplier_value: f64, modifiers: Vec<models::ContractsV1ContractsPuuidGet200ResponseProcessedMatchesInnerXpGrantsModifierModifiersInner>) -> ContractsV1ContractsPuuidGet200ResponseProcessedMatchesInnerXpGrantsModifier {
        ContractsV1ContractsPuuidGet200ResponseProcessedMatchesInnerXpGrantsModifier {
            value,
            base_multiplier_value,
            modifiers,
        }
    }
}

