/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContractDefinitionsV3ItemUpgradesGet200ResponseDefinitionsInnerProgressionSchedule {
    #[serde(rename = "Name")]
    pub name: String,
    /// Currency ID
    #[serde(rename = "ProgressionCurrencyID")]
    pub progression_currency_id: String,
    #[serde(rename = "ProgressionDeltaPerLevel", deserialize_with = "Option::deserialize")]
    pub progression_delta_per_level: Option<Vec<f64>>,
}

impl ContractDefinitionsV3ItemUpgradesGet200ResponseDefinitionsInnerProgressionSchedule {
    pub fn new(name: String, progression_currency_id: String, progression_delta_per_level: Option<Vec<f64>>) -> ContractDefinitionsV3ItemUpgradesGet200ResponseDefinitionsInnerProgressionSchedule {
        ContractDefinitionsV3ItemUpgradesGet200ResponseDefinitionsInnerProgressionSchedule {
            name,
            progression_currency_id,
            progression_delta_per_level,
        }
    }
}

