/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContractDefinitionsV3ItemUpgradesGet200ResponseDefinitionsInnerRewardScheduleRewardsPerLevelInner {
    #[serde(rename = "EntitlementRewards")]
    pub entitlement_rewards: Vec<models::ContractDefinitionsV3ItemUpgradesGet200ResponseDefinitionsInnerRewardScheduleRewardsPerLevelInnerEntitlementRewardsInner>,
    #[serde(rename = "WalletRewards", deserialize_with = "Option::deserialize")]
    pub wallet_rewards: Option<serde_json::Value>,
    #[serde(rename = "CounterRewards", deserialize_with = "Option::deserialize")]
    pub counter_rewards: Option<serde_json::Value>,
}

impl ContractDefinitionsV3ItemUpgradesGet200ResponseDefinitionsInnerRewardScheduleRewardsPerLevelInner {
    pub fn new(entitlement_rewards: Vec<models::ContractDefinitionsV3ItemUpgradesGet200ResponseDefinitionsInnerRewardScheduleRewardsPerLevelInnerEntitlementRewardsInner>, wallet_rewards: Option<serde_json::Value>, counter_rewards: Option<serde_json::Value>) -> ContractDefinitionsV3ItemUpgradesGet200ResponseDefinitionsInnerRewardScheduleRewardsPerLevelInner {
        ContractDefinitionsV3ItemUpgradesGet200ResponseDefinitionsInnerRewardScheduleRewardsPerLevelInner {
            entitlement_rewards,
            wallet_rewards,
            counter_rewards,
        }
    }
}

