/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContractDefinitionsV3ItemUpgradesGet200ResponseDefinitionsInnerSidegradesInnerOptionsInnerCostWalletCostsInner
{
    /// Currency ID
    #[serde(rename = "CurrencyID")]
    pub currency_id: String,
    #[serde(rename = "AmountToDeduct")]
    pub amount_to_deduct: f64,
}

impl ContractDefinitionsV3ItemUpgradesGet200ResponseDefinitionsInnerSidegradesInnerOptionsInnerCostWalletCostsInner {
    pub fn new(currency_id: String, amount_to_deduct: f64) -> ContractDefinitionsV3ItemUpgradesGet200ResponseDefinitionsInnerSidegradesInnerOptionsInnerCostWalletCostsInner {
        ContractDefinitionsV3ItemUpgradesGet200ResponseDefinitionsInnerSidegradesInnerOptionsInnerCostWalletCostsInner {
            currency_id,
            amount_to_deduct,
        }
    }
}
