/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContractsV1ContractsPuuidGet200ResponseMissionMetadata {
    #[serde(rename = "NPECompleted")]
    pub npe_completed: bool,
    /// Date in ISO 8601 format
    #[serde(rename = "WeeklyCheckpoint")]
    pub weekly_checkpoint: String,
    /// Date in ISO 8601 format
    #[serde(rename = "WeeklyRefillTime")]
    pub weekly_refill_time: String,
}

impl ContractsV1ContractsPuuidGet200ResponseMissionMetadata {
    pub fn new(
        npe_completed: bool,
        weekly_checkpoint: String,
        weekly_refill_time: String,
    ) -> ContractsV1ContractsPuuidGet200ResponseMissionMetadata {
        ContractsV1ContractsPuuidGet200ResponseMissionMetadata {
            npe_completed,
            weekly_checkpoint,
            weekly_refill_time,
        }
    }
}
