/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContractDefinitionsV3ItemUpgradesGet200ResponseDefinitionsInnerSidegradesInnerPrerequisites {
    #[serde(rename = "RequiredEntitlements")]
    pub required_entitlements: Vec<models::ContractDefinitionsV3ItemUpgradesGet200ResponseDefinitionsInnerItem>,
}

impl ContractDefinitionsV3ItemUpgradesGet200ResponseDefinitionsInnerSidegradesInnerPrerequisites {
    pub fn new(required_entitlements: Vec<models::ContractDefinitionsV3ItemUpgradesGet200ResponseDefinitionsInnerItem>) -> ContractDefinitionsV3ItemUpgradesGet200ResponseDefinitionsInnerSidegradesInnerPrerequisites {
        ContractDefinitionsV3ItemUpgradesGet200ResponseDefinitionsInnerSidegradesInnerPrerequisites {
            required_entitlements,
        }
    }
}

