/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MatchDetailsV1MatchesMatchIdGet200ResponsePlayersInnerPreferredLevelBorder : Preferred Level Border ID
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MatchDetailsV1MatchesMatchIdGet200ResponsePlayersInnerPreferredLevelBorder {}

impl MatchDetailsV1MatchesMatchIdGet200ResponsePlayersInnerPreferredLevelBorder {
    /// Preferred Level Border ID
    pub fn new() -> MatchDetailsV1MatchesMatchIdGet200ResponsePlayersInnerPreferredLevelBorder {
        MatchDetailsV1MatchesMatchIdGet200ResponsePlayersInnerPreferredLevelBorder {}
    }
}
