/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MatchDetailsV1MatchesMatchIdGet200ResponsePlayersInnerRoundDamageInner {
    #[serde(rename = "round")]
    pub round: f64,
    /// Player UUID
    #[serde(rename = "receiver")]
    pub receiver: String,
    #[serde(rename = "damage")]
    pub damage: f64,
}

impl MatchDetailsV1MatchesMatchIdGet200ResponsePlayersInnerRoundDamageInner {
    pub fn new(round: f64, receiver: String, damage: f64) -> MatchDetailsV1MatchesMatchIdGet200ResponsePlayersInnerRoundDamageInner {
        MatchDetailsV1MatchesMatchIdGet200ResponsePlayersInnerRoundDamageInner {
            round,
            receiver,
            damage,
        }
    }
}

