/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MatchDetailsV1MatchesMatchIdGet200ResponsePlayersInnerTeamId {}

impl MatchDetailsV1MatchesMatchIdGet200ResponsePlayersInnerTeamId {
    pub fn new() -> MatchDetailsV1MatchesMatchIdGet200ResponsePlayersInnerTeamId {
        MatchDetailsV1MatchesMatchIdGet200ResponsePlayersInnerTeamId {}
    }
}
