/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MatchHistoryV1HistoryPuuidGet200ResponseHistoryInner {
    /// Match ID
    #[serde(rename = "MatchID")]
    pub match_id: String,
    /// Milliseconds since epoch
    #[serde(rename = "GameStartTime")]
    pub game_start_time: f64,
    /// Queue ID
    #[serde(rename = "QueueID")]
    pub queue_id: String,
}

impl MatchHistoryV1HistoryPuuidGet200ResponseHistoryInner {
    pub fn new(
        match_id: String,
        game_start_time: f64,
        queue_id: String,
    ) -> MatchHistoryV1HistoryPuuidGet200ResponseHistoryInner {
        MatchHistoryV1HistoryPuuidGet200ResponseHistoryInner {
            match_id,
            game_start_time,
            queue_id,
        }
    }
}
