/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MatchDetailsV1MatchesMatchIdGet200ResponsePlayersInnerXpModificationsInner {
    /// XP multiplier
    #[serde(rename = "Value")]
    pub value: f64,
    /// XP Modification ID
    #[serde(rename = "ID")]
    pub id: String,
}

impl MatchDetailsV1MatchesMatchIdGet200ResponsePlayersInnerXpModificationsInner {
    pub fn new(value: f64, id: String) -> MatchDetailsV1MatchesMatchIdGet200ResponsePlayersInnerXpModificationsInner {
        MatchDetailsV1MatchesMatchIdGet200ResponsePlayersInnerXpModificationsInner {
            value,
            id,
        }
    }
}

