/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MmrV1LeaderboardsAffinityNaQueueCompetitiveSeasonSeasonIdGet200ResponseTierDetailsValue {
    #[serde(rename = "rankedRatingThreshold")]
    pub ranked_rating_threshold: f64,
    #[serde(rename = "startingPage")]
    pub starting_page: f64,
    #[serde(rename = "startingIndex")]
    pub starting_index: f64,
}

impl MmrV1LeaderboardsAffinityNaQueueCompetitiveSeasonSeasonIdGet200ResponseTierDetailsValue {
    pub fn new(
        ranked_rating_threshold: f64,
        starting_page: f64,
        starting_index: f64,
    ) -> MmrV1LeaderboardsAffinityNaQueueCompetitiveSeasonSeasonIdGet200ResponseTierDetailsValue
    {
        MmrV1LeaderboardsAffinityNaQueueCompetitiveSeasonSeasonIdGet200ResponseTierDetailsValue {
            ranked_rating_threshold,
            starting_page,
            starting_index,
        }
    }
}
