/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MmrV1PlayersPuuidGet200ResponseQueueSkillsValue {
    #[serde(rename = "TotalGamesNeededForRating")]
    pub total_games_needed_for_rating: f64,
    #[serde(rename = "TotalGamesNeededForLeaderboard")]
    pub total_games_needed_for_leaderboard: f64,
    #[serde(rename = "CurrentSeasonGamesNeededForRating")]
    pub current_season_games_needed_for_rating: f64,
    #[serde(rename = "SeasonalInfoBySeasonID")]
    pub seasonal_info_by_season_id: std::collections::HashMap<
        String,
        models::MmrV1PlayersPuuidGet200ResponseQueueSkillsValueSeasonalInfoBySeasonIdValue,
    >,
}

impl MmrV1PlayersPuuidGet200ResponseQueueSkillsValue {
    pub fn new(
        total_games_needed_for_rating: f64,
        total_games_needed_for_leaderboard: f64,
        current_season_games_needed_for_rating: f64,
        seasonal_info_by_season_id: std::collections::HashMap<
            String,
            models::MmrV1PlayersPuuidGet200ResponseQueueSkillsValueSeasonalInfoBySeasonIdValue,
        >,
    ) -> MmrV1PlayersPuuidGet200ResponseQueueSkillsValue {
        MmrV1PlayersPuuidGet200ResponseQueueSkillsValue {
            total_games_needed_for_rating,
            total_games_needed_for_leaderboard,
            current_season_games_needed_for_rating,
            seasonal_info_by_season_id,
        }
    }
}
