/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PersonalizationV2PlayersPuuidPlayerloadoutGet200ResponseIdentity {
    /// UUID
    #[serde(rename = "PlayerCardID")]
    pub player_card_id: String,
    /// UUID
    #[serde(rename = "PlayerTitleID")]
    pub player_title_id: String,
    #[serde(rename = "AccountLevel")]
    pub account_level: f64,
    /// UUID
    #[serde(rename = "PreferredLevelBorderID")]
    pub preferred_level_border_id: String,
    #[serde(rename = "HideAccountLevel")]
    pub hide_account_level: bool,
}

impl PersonalizationV2PlayersPuuidPlayerloadoutGet200ResponseIdentity {
    pub fn new(
        player_card_id: String,
        player_title_id: String,
        account_level: f64,
        preferred_level_border_id: String,
        hide_account_level: bool,
    ) -> PersonalizationV2PlayersPuuidPlayerloadoutGet200ResponseIdentity {
        PersonalizationV2PlayersPuuidPlayerloadoutGet200ResponseIdentity {
            player_card_id,
            player_title_id,
            account_level,
            preferred_level_border_id,
            hide_account_level,
        }
    }
}
