/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PersonalizationV2PlayersPuuidPlayerloadoutGet200ResponseSpraysInner {
    /// UUID
    #[serde(rename = "EquipSlotID")]
    pub equip_slot_id: String,
    /// UUID
    #[serde(rename = "SprayID")]
    pub spray_id: String,
    #[serde(rename = "SprayLevelID", deserialize_with = "Option::deserialize")]
    pub spray_level_id: Option<serde_json::Value>,
}

impl PersonalizationV2PlayersPuuidPlayerloadoutGet200ResponseSpraysInner {
    pub fn new(
        equip_slot_id: String,
        spray_id: String,
        spray_level_id: Option<serde_json::Value>,
    ) -> PersonalizationV2PlayersPuuidPlayerloadoutGet200ResponseSpraysInner {
        PersonalizationV2PlayersPuuidPlayerloadoutGet200ResponseSpraysInner {
            equip_slot_id,
            spray_id,
            spray_level_id,
        }
    }
}
