/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RestrictionsV3PenaltiesGet200Response {
    /// Player UUID
    #[serde(rename = "Subject")]
    pub subject: String,
    #[serde(rename = "Penalties")]
    pub penalties: Vec<serde_json::Value>,
    #[serde(rename = "Version")]
    pub version: f64,
}

impl RestrictionsV3PenaltiesGet200Response {
    pub fn new(subject: String, penalties: Vec<serde_json::Value>, version: f64) -> RestrictionsV3PenaltiesGet200Response {
        RestrictionsV3PenaltiesGet200Response {
            subject,
            penalties,
            version,
        }
    }
}

