/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StoreV2StorefrontPuuidGet200Response {
    #[serde(rename = "FeaturedBundle")]
    pub featured_bundle: Box<models::StoreV2StorefrontPuuidGet200ResponseFeaturedBundle>,
    #[serde(rename = "SkinsPanelLayout")]
    pub skins_panel_layout: Box<models::StoreV2StorefrontPuuidGet200ResponseSkinsPanelLayout>,
    #[serde(rename = "UpgradeCurrencyStore")]
    pub upgrade_currency_store:
        Box<models::StoreV2StorefrontPuuidGet200ResponseUpgradeCurrencyStore>,
    #[serde(rename = "AccessoryStore")]
    pub accessory_store: Box<models::StoreV2StorefrontPuuidGet200ResponseAccessoryStore>,
    #[serde(rename = "BonusStore", skip_serializing_if = "Option::is_none")]
    pub bonus_store: Option<Box<models::StoreV2StorefrontPuuidGet200ResponseBonusStore>>,
}

impl StoreV2StorefrontPuuidGet200Response {
    pub fn new(
        featured_bundle: models::StoreV2StorefrontPuuidGet200ResponseFeaturedBundle,
        skins_panel_layout: models::StoreV2StorefrontPuuidGet200ResponseSkinsPanelLayout,
        upgrade_currency_store: models::StoreV2StorefrontPuuidGet200ResponseUpgradeCurrencyStore,
        accessory_store: models::StoreV2StorefrontPuuidGet200ResponseAccessoryStore,
    ) -> StoreV2StorefrontPuuidGet200Response {
        StoreV2StorefrontPuuidGet200Response {
            featured_bundle: Box::new(featured_bundle),
            skins_panel_layout: Box::new(skins_panel_layout),
            upgrade_currency_store: Box::new(upgrade_currency_store),
            accessory_store: Box::new(accessory_store),
            bonus_store: None,
        }
    }
}
