/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StoreV2StorefrontPuuidGet200ResponseFeaturedBundle {
    #[serde(rename = "Bundle")]
    pub bundle: Box<models::StoreV2StorefrontPuuidGet200ResponseFeaturedBundleBundle>,
    #[serde(rename = "Bundles")]
    pub bundles: Vec<models::StoreV2StorefrontPuuidGet200ResponseFeaturedBundleBundle>,
    #[serde(rename = "BundleRemainingDurationInSeconds")]
    pub bundle_remaining_duration_in_seconds: f64,
}

impl StoreV2StorefrontPuuidGet200ResponseFeaturedBundle {
    pub fn new(bundle: models::StoreV2StorefrontPuuidGet200ResponseFeaturedBundleBundle, bundles: Vec<models::StoreV2StorefrontPuuidGet200ResponseFeaturedBundleBundle>, bundle_remaining_duration_in_seconds: f64) -> StoreV2StorefrontPuuidGet200ResponseFeaturedBundle {
        StoreV2StorefrontPuuidGet200ResponseFeaturedBundle {
            bundle: Box::new(bundle),
            bundles,
            bundle_remaining_duration_in_seconds,
        }
    }
}

