/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StoreV2StorefrontPuuidGet200ResponseAccessoryStoreAccessoryStoreOffersInner {
    #[serde(rename = "Offer")]
    pub offer: Box<models::StoreV1OffersGet200ResponseOffersInner>,
    /// UUID
    #[serde(rename = "ContractID")]
    pub contract_id: String,
}

impl StoreV2StorefrontPuuidGet200ResponseAccessoryStoreAccessoryStoreOffersInner {
    pub fn new(
        offer: models::StoreV1OffersGet200ResponseOffersInner,
        contract_id: String,
    ) -> StoreV2StorefrontPuuidGet200ResponseAccessoryStoreAccessoryStoreOffersInner {
        StoreV2StorefrontPuuidGet200ResponseAccessoryStoreAccessoryStoreOffersInner {
            offer: Box::new(offer),
            contract_id,
        }
    }
}
