/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StoreV2StorefrontPuuidGet200ResponseAccessoryStore {
    #[serde(rename = "AccessoryStoreOffers")]
    pub accessory_store_offers:
        Vec<models::StoreV2StorefrontPuuidGet200ResponseAccessoryStoreAccessoryStoreOffersInner>,
    #[serde(rename = "AccessoryStoreRemainingDurationInSeconds")]
    pub accessory_store_remaining_duration_in_seconds: f64,
    /// UUID
    #[serde(rename = "StorefrontID")]
    pub storefront_id: String,
}

impl StoreV2StorefrontPuuidGet200ResponseAccessoryStore {
    pub fn new(
        accessory_store_offers: Vec<
            models::StoreV2StorefrontPuuidGet200ResponseAccessoryStoreAccessoryStoreOffersInner,
        >,
        accessory_store_remaining_duration_in_seconds: f64,
        storefront_id: String,
    ) -> StoreV2StorefrontPuuidGet200ResponseAccessoryStore {
        StoreV2StorefrontPuuidGet200ResponseAccessoryStore {
            accessory_store_offers,
            accessory_store_remaining_duration_in_seconds,
            storefront_id,
        }
    }
}
