/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StoreV2StorefrontPuuidGet200ResponseBonusStore : Night market
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StoreV2StorefrontPuuidGet200ResponseBonusStore {
    #[serde(rename = "BonusStoreOffers")]
    pub bonus_store_offers:
        Vec<models::StoreV2StorefrontPuuidGet200ResponseBonusStoreBonusStoreOffersInner>,
    #[serde(rename = "BonusStoreRemainingDurationInSeconds")]
    pub bonus_store_remaining_duration_in_seconds: f64,
}

impl StoreV2StorefrontPuuidGet200ResponseBonusStore {
    /// Night market
    pub fn new(
        bonus_store_offers: Vec<
            models::StoreV2StorefrontPuuidGet200ResponseBonusStoreBonusStoreOffersInner,
        >,
        bonus_store_remaining_duration_in_seconds: f64,
    ) -> StoreV2StorefrontPuuidGet200ResponseBonusStore {
        StoreV2StorefrontPuuidGet200ResponseBonusStore {
            bonus_store_offers,
            bonus_store_remaining_duration_in_seconds,
        }
    }
}
