/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StoreV2StorefrontPuuidGet200ResponseUpgradeCurrencyStore {
    #[serde(rename = "UpgradeCurrencyOffers")]
    pub upgrade_currency_offers: Vec<models::StoreV2StorefrontPuuidGet200ResponseUpgradeCurrencyStoreUpgradeCurrencyOffersInner>,
}

impl StoreV2StorefrontPuuidGet200ResponseUpgradeCurrencyStore {
    pub fn new(upgrade_currency_offers: Vec<models::StoreV2StorefrontPuuidGet200ResponseUpgradeCurrencyStoreUpgradeCurrencyOffersInner>) -> StoreV2StorefrontPuuidGet200ResponseUpgradeCurrencyStore {
        StoreV2StorefrontPuuidGet200ResponseUpgradeCurrencyStore {
            upgrade_currency_offers,
        }
    }
}

