/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StoreV1WalletPuuidGet200Response {
    #[serde(rename = "Balances")]
    pub balances: std::collections::HashMap<String, f64>,
}

impl StoreV1WalletPuuidGet200Response {
    pub fn new(
        balances: std::collections::HashMap<String, f64>,
    ) -> StoreV1WalletPuuidGet200Response {
        StoreV1WalletPuuidGet200Response { balances }
    }
}
