/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StoreV1EntitlementsPuuidItemTypeIdGet200ResponseEntitlementsByTypesInner {
    #[serde(rename = "ItemTypeID")]
    pub item_type_id: String,
    #[serde(rename = "Entitlements")]
    pub entitlements: Vec<models::StoreV1EntitlementsPuuidItemTypeIdGet200ResponseEntitlementsByTypesInnerEntitlementsInner>,
}

impl StoreV1EntitlementsPuuidItemTypeIdGet200ResponseEntitlementsByTypesInner {
    pub fn new(item_type_id: String, entitlements: Vec<models::StoreV1EntitlementsPuuidItemTypeIdGet200ResponseEntitlementsByTypesInnerEntitlementsInner>) -> StoreV1EntitlementsPuuidItemTypeIdGet200ResponseEntitlementsByTypesInner {
        StoreV1EntitlementsPuuidItemTypeIdGet200ResponseEntitlementsByTypesInner {
            item_type_id,
            entitlements,
        }
    }
}

