/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StoreV2StorefrontPuuidGet200ResponseSkinsPanelLayout {
    #[serde(rename = "SingleItemOffers")]
    pub single_item_offers: Vec<String>,
    #[serde(rename = "SingleItemStoreOffers")]
    pub single_item_store_offers: Vec<models::StoreV1OffersGet200ResponseOffersInner>,
    #[serde(rename = "SingleItemOffersRemainingDurationInSeconds")]
    pub single_item_offers_remaining_duration_in_seconds: f64,
}

impl StoreV2StorefrontPuuidGet200ResponseSkinsPanelLayout {
    pub fn new(single_item_offers: Vec<String>, single_item_store_offers: Vec<models::StoreV1OffersGet200ResponseOffersInner>, single_item_offers_remaining_duration_in_seconds: f64) -> StoreV2StorefrontPuuidGet200ResponseSkinsPanelLayout {
        StoreV2StorefrontPuuidGet200ResponseSkinsPanelLayout {
            single_item_offers,
            single_item_store_offers,
            single_item_offers_remaining_duration_in_seconds,
        }
    }
}

