/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StoreV1OffersGet200Response {
    #[serde(rename = "Offers")]
    pub offers: Vec<models::StoreV1OffersGet200ResponseOffersInner>,
}

impl StoreV1OffersGet200Response {
    pub fn new(
        offers: Vec<models::StoreV1OffersGet200ResponseOffersInner>,
    ) -> StoreV1OffersGet200Response {
        StoreV1OffersGet200Response { offers }
    }
}
