/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1ConfigRegionGet200ResponseCollapsed {
    #[serde(rename = "ARES_MOC_ENTITLEMENT")]
    pub ares_moc_entitlement: String,
    #[serde(rename = "CLIENT.ICONS.ENABLED")]
    pub client_period_icons_period_enabled: String,
    #[serde(rename = "CLIENT_LEADERBOARDS_ENABLED")]
    pub client_leaderboards_enabled: String,
    #[serde(rename = "GAME_ALLOW_CONSOLE")]
    pub game_allow_console: String,
    #[serde(rename = "GAME_ALLOW_DEVELOPER_MENU")]
    pub game_allow_developer_menu: String,
    #[serde(rename = "GAME_DISABLED_DEATHCAM")]
    pub game_disabled_deathcam: String,
    #[serde(rename = "GAME_DISABLED_SKINS_WEAPONS")]
    pub game_disabled_skins_weapons: String,
    #[serde(rename = "GAME_PERFREPORTING_ENABLED")]
    pub game_perfreporting_enabled: String,
    #[serde(rename = "GAME_REMOTE_MOVE_INTERP_ENABLED")]
    pub game_remote_move_interp_enabled: String,
    #[serde(rename = "GAME_ROAMINGSETTINGS_ENABLED")]
    pub game_roamingsettings_enabled: String,
    #[serde(rename = "GAME_ROAMINGSETTINGS_KEY")]
    pub game_roamingsettings_key: String,
    #[serde(rename = "GAME_ROAMINGSETTINGS_STORAGEURL")]
    pub game_roamingsettings_storageurl: String,
    #[serde(rename = "MAP_PRELOADING_ENABLED")]
    pub map_preloading_enabled: String,
    #[serde(rename = "NAMECHECK_PLATFORM_REGION")]
    pub namecheck_platform_region: String,
    #[serde(rename = "NAMECHECK_PLATFORM_URL")]
    pub namecheck_platform_url: String,
    #[serde(rename = "ROSTER_REALM")]
    pub roster_realm: String,
    #[serde(rename = "SECURITY_WATERMARK_ENABLED")]
    pub security_watermark_enabled: String,
    #[serde(rename = "SECURITY_WATERMARK_MAX_OPACITY")]
    pub security_watermark_max_opacity: String,
    #[serde(rename = "SECURITY_WATERMARK_MIN_OPACITY")]
    pub security_watermark_min_opacity: String,
    #[serde(rename = "SECURITY_WATERMARK_TILING_FACTOR")]
    pub security_watermark_tiling_factor: String,
    #[serde(rename = "SERVICEURL_ACCOUNT_XP")]
    pub serviceurl_account_xp: String,
    #[serde(rename = "SERVICEURL_AGGSTATS")]
    pub serviceurl_aggstats: String,
    #[serde(rename = "SERVICEURL_AVS")]
    pub serviceurl_avs: String,
    #[serde(rename = "SERVICEURL_CONTENT")]
    pub serviceurl_content: String,
    #[serde(rename = "SERVICEURL_CONTRACTS")]
    pub serviceurl_contracts: String,
    #[serde(rename = "SERVICEURL_CONTRACT_DEFINITIONS")]
    pub serviceurl_contract_definitions: String,
    #[serde(rename = "SERVICEURL_COREGAME")]
    pub serviceurl_coregame: String,
    #[serde(rename = "SERVICEURL_DAILY_TICKET")]
    pub serviceurl_daily_ticket: String,
    #[serde(rename = "SERVICEURL_FAVORITES")]
    pub serviceurl_favorites: String,
    #[serde(rename = "SERVICEURL_GALBS_QUERY")]
    pub serviceurl_galbs_query: String,
    #[serde(rename = "SERVICEURL_LATENCY")]
    pub serviceurl_latency: String,
    #[serde(rename = "SERVICEURL_LOGINQUEUE")]
    pub serviceurl_loginqueue: String,
    #[serde(rename = "SERVICEURL_MASS_REWARDS")]
    pub serviceurl_mass_rewards: String,
    #[serde(rename = "SERVICEURL_MATCHDETAILS")]
    pub serviceurl_matchdetails: String,
    #[serde(rename = "SERVICEURL_MATCHHISTORY")]
    pub serviceurl_matchhistory: String,
    #[serde(rename = "SERVICEURL_MATCHMAKING")]
    pub serviceurl_matchmaking: String,
    #[serde(rename = "SERVICEURL_MMR")]
    pub serviceurl_mmr: String,
    #[serde(rename = "SERVICEURL_NAME")]
    pub serviceurl_name: String,
    #[serde(rename = "SERVICEURL_PARTY")]
    pub serviceurl_party: String,
    #[serde(rename = "SERVICEURL_PATCHNOTES")]
    pub serviceurl_patchnotes: String,
    #[serde(rename = "SERVICEURL_PERSONALIZATION")]
    pub serviceurl_personalization: String,
    #[serde(rename = "SERVICEURL_PLAYERFEEDBACK")]
    pub serviceurl_playerfeedback: String,
    #[serde(rename = "SERVICEURL_PREGAME")]
    pub serviceurl_pregame: String,
    #[serde(rename = "SERVICEURL_PREMIER")]
    pub serviceurl_premier: String,
    #[serde(rename = "SERVICEURL_PROGRESSION")]
    pub serviceurl_progression: String,
    #[serde(rename = "SERVICEURL_PURCHASEMERCHANT")]
    pub serviceurl_purchasemerchant: String,
    #[serde(rename = "SERVICEURL_REPLAY_CATALOG")]
    pub serviceurl_replay_catalog: String,
    #[serde(rename = "SERVICEURL_RESTRICTIONS")]
    pub serviceurl_restrictions: String,
    #[serde(rename = "SERVICEURL_SESSION")]
    pub serviceurl_session: String,
    #[serde(rename = "SERVICEURL_STORE")]
    pub serviceurl_store: String,
    #[serde(rename = "SERVICEURL_TOURNAMENTS")]
    pub serviceurl_tournaments: String,
    #[serde(rename = "SERVICE_TICKER_MESSAGE")]
    pub service_ticker_message: String,
    #[serde(rename = "SERVICE_TICKER_MESSAGE.de-DE")]
    pub service_ticker_message_period_de_de: String,
    #[serde(rename = "SERVICE_TICKER_MESSAGE.es-MX")]
    pub service_ticker_message_period_es_mx: String,
    #[serde(rename = "SERVICE_TICKER_MESSAGE.fr-FR")]
    pub service_ticker_message_period_fr_fr: String,
    #[serde(rename = "SERVICE_TICKER_MESSAGE.it-IT")]
    pub service_ticker_message_period_it_it: String,
    #[serde(rename = "SERVICE_TICKER_MESSAGE.pl-PL")]
    pub service_ticker_message_period_pl_pl: String,
    #[serde(rename = "SERVICE_TICKER_MESSAGE.pt-BR")]
    pub service_ticker_message_period_pt_br: String,
    #[serde(rename = "SERVICE_TICKER_MESSAGE.ru-RU")]
    pub service_ticker_message_period_ru_ru: String,
    #[serde(rename = "SERVICE_TICKER_MESSAGE.tr-TR")]
    pub service_ticker_message_period_tr_tr: String,
    #[serde(rename = "SERVICE_TICKER_SEVERITY")]
    pub service_ticker_severity: String,
    #[serde(rename = "STORESCREEN_OFFERREFRESH_MAXDELAY_MILLISECONDS")]
    pub storescreen_offerrefresh_maxdelay_milliseconds: String,
    #[serde(rename = "avs.enabled")]
    pub avs_period_enabled: String,
    #[serde(rename = "cap.location")]
    pub cap_period_location: String,
    #[serde(rename = "characterselect.debugwidgets.hide")]
    pub characterselect_period_debugwidgets_period_hide: String,
    #[serde(rename = "chat.mutedwords.enabled")]
    pub chat_period_mutedwords_period_enabled: String,
    #[serde(rename = "chat.v3.enabled")]
    pub chat_period_v3_period_enabled: String,
    #[serde(rename = "collection.characters.enabled")]
    pub collection_period_characters_period_enabled: String,
    #[serde(rename = "competitiveSeasonOffsetEndTime")]
    pub competitive_season_offset_end_time: String,
    #[serde(rename = "config.client.telemetry.samplerate")]
    pub config_period_client_period_telemetry_period_samplerate: String,
    #[serde(rename = "content.filter.enabled")]
    pub content_period_filter_period_enabled: String,
    #[serde(rename = "content.maps.disabled")]
    pub content_period_maps_period_disabled: String,
    #[serde(rename = "eog.wip")]
    pub eog_period_wip: String,
    #[serde(rename = "friends.enabled")]
    pub friends_period_enabled: String,
    #[serde(rename = "game.umgchat.enabled")]
    pub game_period_umgchat_period_enabled: String,
    #[serde(rename = "homescreen.featuredQueues")]
    pub homescreen_period_featured_queues: String,
    #[serde(rename = "homescreen.patchnotes.baseURL")]
    pub homescreen_period_patchnotes_period_base_url: String,
    #[serde(rename = "homescreen.promo.enabled")]
    pub homescreen_period_promo_period_enabled: String,
    #[serde(rename = "homescreen.promo.key")]
    pub homescreen_period_promo_period_key: String,
    #[serde(rename = "homescreen.webtile.baseURL")]
    pub homescreen_period_webtile_period_base_url: String,
    #[serde(rename = "loginqueue.region")]
    pub loginqueue_period_region: String,
    #[serde(rename = "mainmenubar.collections.enabled")]
    pub mainmenubar_period_collections_period_enabled: String,
    #[serde(rename = "mainmenubar.debug.enabled")]
    pub mainmenubar_period_debug_period_enabled: String,
    #[serde(rename = "mainmenubar.profile.enabled")]
    pub mainmenubar_period_profile_period_enabled: String,
    #[serde(rename = "mainmenubar.progression.enabled")]
    pub mainmenubar_period_progression_period_enabled: String,
    #[serde(rename = "mainmenubar.shootingrange.enabled")]
    pub mainmenubar_period_shootingrange_period_enabled: String,
    #[serde(rename = "mainmenubar.store.enabled")]
    pub mainmenubar_period_store_period_enabled: String,
    #[serde(rename = "match.details.delay")]
    pub match_period_details_period_delay: String,
    #[serde(rename = "notifications.enabled")]
    pub notifications_period_enabled: String,
    #[serde(rename = "parties.auto.balance.enabled")]
    pub parties_period_auto_period_balance_period_enabled: String,
    #[serde(rename = "party.observers.enabled")]
    pub party_period_observers_period_enabled: String,
    #[serde(rename = "partyinvites.enabled")]
    pub partyinvites_period_enabled: String,
    #[serde(rename = "patchavailability.enabled")]
    pub patchavailability_period_enabled: String,
    #[serde(rename = "personalization.equipAnyLevel.enabled")]
    pub personalization_period_equip_any_level_period_enabled: String,
    #[serde(rename = "personalization.useWidePlayerIdentityV2")]
    pub personalization_period_use_wide_player_identity_v2: String,
    #[serde(rename = "ping.update.interval")]
    pub ping_period_update_period_interval: String,
    #[serde(rename = "ping.useGamePodsFromParties")]
    pub ping_period_use_game_pods_from_parties: String,
    #[serde(rename = "platformFaulted.level")]
    pub platform_faulted_period_level: String,
    #[serde(rename = "playerfeedbacktool.accessurl")]
    pub playerfeedbacktool_period_accessurl: String,
    #[serde(rename = "playerfeedbacktool.locale")]
    pub playerfeedbacktool_period_locale: String,
    #[serde(rename = "playerfeedbacktool.shard")]
    pub playerfeedbacktool_period_shard: String,
    #[serde(rename = "playerfeedbacktool.show")]
    pub playerfeedbacktool_period_show: String,
    #[serde(rename = "playerfeedbacktool.survey_request_rate_float")]
    pub playerfeedbacktool_period_survey_request_rate_float: String,
    #[serde(rename = "playscreen.partywidget.enabled")]
    pub playscreen_period_partywidget_period_enabled: String,
    #[serde(rename = "playscreen.partywidget.matchmaking.maxsize")]
    pub playscreen_period_partywidget_period_matchmaking_period_maxsize: String,
    #[serde(rename = "playscreen.premier.enabled")]
    pub playscreen_period_premier_period_enabled: String,
    #[serde(rename = "premier.conferences.fetch.enabled")]
    pub premier_period_conferences_period_fetch_period_enabled: String,
    #[serde(rename = "premier.leaderboardTab.enabled")]
    pub premier_period_leaderboard_tab_period_enabled: String,
    #[serde(rename = "premier.matchHistoryTab.enabled")]
    pub premier_period_match_history_tab_period_enabled: String,
    #[serde(rename = "premier.playscreenflow.enabled")]
    pub premier_period_playscreenflow_period_enabled: String,
    #[serde(rename = "premier.rosterEligibilityCheck.enabled")]
    pub premier_period_roster_eligibility_check_period_enabled: String,
    #[serde(rename = "premier.seasons.activeseason.enabled")]
    pub premier_period_seasons_period_activeseason_period_enabled: String,
    #[serde(rename = "premier.seasons.fetch.enabled")]
    pub premier_period_seasons_period_fetch_period_enabled: String,
    #[serde(rename = "queue.status.enabled")]
    pub queue_period_status_period_enabled: String,
    #[serde(rename = "rchat.ingame.enabled")]
    pub rchat_period_ingame_period_enabled: String,
    #[serde(rename = "reporterfeedback.fetch.enabled")]
    pub reporterfeedback_period_fetch_period_enabled: String,
    #[serde(rename = "reporterfeedback.notifications.enabled")]
    pub reporterfeedback_period_notifications_period_enabled: String,
    #[serde(rename = "restrictions.v2.fetch.enabled")]
    pub restrictions_period_v2_period_fetch_period_enabled: String,
    #[serde(rename = "restrictions.v2.warnings.enabled")]
    pub restrictions_period_v2_period_warnings_period_enabled: String,
    #[serde(rename = "riotwarning.fetch.enabled")]
    pub riotwarning_period_fetch_period_enabled: String,
    #[serde(rename = "riotwarning.notifications.enabled")]
    pub riotwarning_period_notifications_period_enabled: String,
    #[serde(rename = "rnet.useAuthenticatedVoice")]
    pub rnet_period_use_authenticated_voice: String,
    #[serde(rename = "russia.voice.enabled")]
    pub russia_period_voice_period_enabled: String,
    /// Comma separated list of PUUIDs
    #[serde(rename = "settings.livediagnostics.allowedplayers")]
    pub settings_period_livediagnostics_period_allowedplayers: String,
    #[serde(rename = "shootingtest.enabled")]
    pub shootingtest_period_enabled: String,
    #[serde(rename = "skillrating.enabled")]
    pub skillrating_period_enabled: String,
    #[serde(rename = "skillrating.inGame.enabled")]
    pub skillrating_period_in_game_period_enabled: String,
    #[serde(rename = "skillrating.preGame.enabled")]
    pub skillrating_period_pre_game_period_enabled: String,
    #[serde(rename = "social.panel.v6.enabled")]
    pub social_period_panel_period_v6_period_enabled: String,
    #[serde(rename = "socialviewcontroller.enabled")]
    pub socialviewcontroller_period_enabled: String,
    #[serde(rename = "socialviewcontroller.v2.enabled")]
    pub socialviewcontroller_period_v2_period_enabled: String,
    #[serde(rename = "store.isXgpDisabled")]
    pub store_period_is_xgp_disabled: String,
    #[serde(rename = "store.use_currency_inventory_models")]
    pub store_period_use_currency_inventory_models: String,
    #[serde(rename = "store.use_platform_bundle_discounted_prices")]
    pub store_period_use_platform_bundle_discounted_prices: String,
    #[serde(rename = "telemetry.rtp.eventendpoint")]
    pub telemetry_period_rtp_period_eventendpoint: String,
    #[serde(rename = "telemetry.rtp.rfc190scope")]
    pub telemetry_period_rtp_period_rfc190scope: String,
    #[serde(rename = "temp.voice.allowmuting")]
    pub temp_period_voice_period_allowmuting: String,
    #[serde(rename = "tournaments.enabled")]
    pub tournaments_period_enabled: String,
    #[serde(rename = "tournaments.pregame.enabled")]
    pub tournaments_period_pregame_period_enabled: String,
    #[serde(rename = "vanguard.accessurl")]
    pub vanguard_period_accessurl: String,
    #[serde(rename = "vanguard.netrequired")]
    pub vanguard_period_netrequired: String,
    #[serde(rename = "voice.clutchmute.enabled")]
    pub voice_period_clutchmute_period_enabled: String,
    #[serde(rename = "voice.clutchmute.prompt.enabled")]
    pub voice_period_clutchmute_period_prompt_period_enabled: String,
    #[serde(rename = "voice.provider")]
    pub voice_period_provider: String,
    #[serde(rename = "whisper.enabled")]
    pub whisper_period_enabled: String,
}

impl V1ConfigRegionGet200ResponseCollapsed {
    pub fn new(
        ares_moc_entitlement: String,
        client_period_icons_period_enabled: String,
        client_leaderboards_enabled: String,
        game_allow_console: String,
        game_allow_developer_menu: String,
        game_disabled_deathcam: String,
        game_disabled_skins_weapons: String,
        game_perfreporting_enabled: String,
        game_remote_move_interp_enabled: String,
        game_roamingsettings_enabled: String,
        game_roamingsettings_key: String,
        game_roamingsettings_storageurl: String,
        map_preloading_enabled: String,
        namecheck_platform_region: String,
        namecheck_platform_url: String,
        roster_realm: String,
        security_watermark_enabled: String,
        security_watermark_max_opacity: String,
        security_watermark_min_opacity: String,
        security_watermark_tiling_factor: String,
        serviceurl_account_xp: String,
        serviceurl_aggstats: String,
        serviceurl_avs: String,
        serviceurl_content: String,
        serviceurl_contracts: String,
        serviceurl_contract_definitions: String,
        serviceurl_coregame: String,
        serviceurl_daily_ticket: String,
        serviceurl_favorites: String,
        serviceurl_galbs_query: String,
        serviceurl_latency: String,
        serviceurl_loginqueue: String,
        serviceurl_mass_rewards: String,
        serviceurl_matchdetails: String,
        serviceurl_matchhistory: String,
        serviceurl_matchmaking: String,
        serviceurl_mmr: String,
        serviceurl_name: String,
        serviceurl_party: String,
        serviceurl_patchnotes: String,
        serviceurl_personalization: String,
        serviceurl_playerfeedback: String,
        serviceurl_pregame: String,
        serviceurl_premier: String,
        serviceurl_progression: String,
        serviceurl_purchasemerchant: String,
        serviceurl_replay_catalog: String,
        serviceurl_restrictions: String,
        serviceurl_session: String,
        serviceurl_store: String,
        serviceurl_tournaments: String,
        service_ticker_message: String,
        service_ticker_message_period_de_de: String,
        service_ticker_message_period_es_mx: String,
        service_ticker_message_period_fr_fr: String,
        service_ticker_message_period_it_it: String,
        service_ticker_message_period_pl_pl: String,
        service_ticker_message_period_pt_br: String,
        service_ticker_message_period_ru_ru: String,
        service_ticker_message_period_tr_tr: String,
        service_ticker_severity: String,
        storescreen_offerrefresh_maxdelay_milliseconds: String,
        avs_period_enabled: String,
        cap_period_location: String,
        characterselect_period_debugwidgets_period_hide: String,
        chat_period_mutedwords_period_enabled: String,
        chat_period_v3_period_enabled: String,
        collection_period_characters_period_enabled: String,
        competitive_season_offset_end_time: String,
        config_period_client_period_telemetry_period_samplerate: String,
        content_period_filter_period_enabled: String,
        content_period_maps_period_disabled: String,
        eog_period_wip: String,
        friends_period_enabled: String,
        game_period_umgchat_period_enabled: String,
        homescreen_period_featured_queues: String,
        homescreen_period_patchnotes_period_base_url: String,
        homescreen_period_promo_period_enabled: String,
        homescreen_period_promo_period_key: String,
        homescreen_period_webtile_period_base_url: String,
        loginqueue_period_region: String,
        mainmenubar_period_collections_period_enabled: String,
        mainmenubar_period_debug_period_enabled: String,
        mainmenubar_period_profile_period_enabled: String,
        mainmenubar_period_progression_period_enabled: String,
        mainmenubar_period_shootingrange_period_enabled: String,
        mainmenubar_period_store_period_enabled: String,
        match_period_details_period_delay: String,
        notifications_period_enabled: String,
        parties_period_auto_period_balance_period_enabled: String,
        party_period_observers_period_enabled: String,
        partyinvites_period_enabled: String,
        patchavailability_period_enabled: String,
        personalization_period_equip_any_level_period_enabled: String,
        personalization_period_use_wide_player_identity_v2: String,
        ping_period_update_period_interval: String,
        ping_period_use_game_pods_from_parties: String,
        platform_faulted_period_level: String,
        playerfeedbacktool_period_accessurl: String,
        playerfeedbacktool_period_locale: String,
        playerfeedbacktool_period_shard: String,
        playerfeedbacktool_period_show: String,
        playerfeedbacktool_period_survey_request_rate_float: String,
        playscreen_period_partywidget_period_enabled: String,
        playscreen_period_partywidget_period_matchmaking_period_maxsize: String,
        playscreen_period_premier_period_enabled: String,
        premier_period_conferences_period_fetch_period_enabled: String,
        premier_period_leaderboard_tab_period_enabled: String,
        premier_period_match_history_tab_period_enabled: String,
        premier_period_playscreenflow_period_enabled: String,
        premier_period_roster_eligibility_check_period_enabled: String,
        premier_period_seasons_period_activeseason_period_enabled: String,
        premier_period_seasons_period_fetch_period_enabled: String,
        queue_period_status_period_enabled: String,
        rchat_period_ingame_period_enabled: String,
        reporterfeedback_period_fetch_period_enabled: String,
        reporterfeedback_period_notifications_period_enabled: String,
        restrictions_period_v2_period_fetch_period_enabled: String,
        restrictions_period_v2_period_warnings_period_enabled: String,
        riotwarning_period_fetch_period_enabled: String,
        riotwarning_period_notifications_period_enabled: String,
        rnet_period_use_authenticated_voice: String,
        russia_period_voice_period_enabled: String,
        settings_period_livediagnostics_period_allowedplayers: String,
        shootingtest_period_enabled: String,
        skillrating_period_enabled: String,
        skillrating_period_in_game_period_enabled: String,
        skillrating_period_pre_game_period_enabled: String,
        social_period_panel_period_v6_period_enabled: String,
        socialviewcontroller_period_enabled: String,
        socialviewcontroller_period_v2_period_enabled: String,
        store_period_is_xgp_disabled: String,
        store_period_use_currency_inventory_models: String,
        store_period_use_platform_bundle_discounted_prices: String,
        telemetry_period_rtp_period_eventendpoint: String,
        telemetry_period_rtp_period_rfc190scope: String,
        temp_period_voice_period_allowmuting: String,
        tournaments_period_enabled: String,
        tournaments_period_pregame_period_enabled: String,
        vanguard_period_accessurl: String,
        vanguard_period_netrequired: String,
        voice_period_clutchmute_period_enabled: String,
        voice_period_clutchmute_period_prompt_period_enabled: String,
        voice_period_provider: String,
        whisper_period_enabled: String,
    ) -> V1ConfigRegionGet200ResponseCollapsed {
        V1ConfigRegionGet200ResponseCollapsed {
            ares_moc_entitlement,
            client_period_icons_period_enabled,
            client_leaderboards_enabled,
            game_allow_console,
            game_allow_developer_menu,
            game_disabled_deathcam,
            game_disabled_skins_weapons,
            game_perfreporting_enabled,
            game_remote_move_interp_enabled,
            game_roamingsettings_enabled,
            game_roamingsettings_key,
            game_roamingsettings_storageurl,
            map_preloading_enabled,
            namecheck_platform_region,
            namecheck_platform_url,
            roster_realm,
            security_watermark_enabled,
            security_watermark_max_opacity,
            security_watermark_min_opacity,
            security_watermark_tiling_factor,
            serviceurl_account_xp,
            serviceurl_aggstats,
            serviceurl_avs,
            serviceurl_content,
            serviceurl_contracts,
            serviceurl_contract_definitions,
            serviceurl_coregame,
            serviceurl_daily_ticket,
            serviceurl_favorites,
            serviceurl_galbs_query,
            serviceurl_latency,
            serviceurl_loginqueue,
            serviceurl_mass_rewards,
            serviceurl_matchdetails,
            serviceurl_matchhistory,
            serviceurl_matchmaking,
            serviceurl_mmr,
            serviceurl_name,
            serviceurl_party,
            serviceurl_patchnotes,
            serviceurl_personalization,
            serviceurl_playerfeedback,
            serviceurl_pregame,
            serviceurl_premier,
            serviceurl_progression,
            serviceurl_purchasemerchant,
            serviceurl_replay_catalog,
            serviceurl_restrictions,
            serviceurl_session,
            serviceurl_store,
            serviceurl_tournaments,
            service_ticker_message,
            service_ticker_message_period_de_de,
            service_ticker_message_period_es_mx,
            service_ticker_message_period_fr_fr,
            service_ticker_message_period_it_it,
            service_ticker_message_period_pl_pl,
            service_ticker_message_period_pt_br,
            service_ticker_message_period_ru_ru,
            service_ticker_message_period_tr_tr,
            service_ticker_severity,
            storescreen_offerrefresh_maxdelay_milliseconds,
            avs_period_enabled,
            cap_period_location,
            characterselect_period_debugwidgets_period_hide,
            chat_period_mutedwords_period_enabled,
            chat_period_v3_period_enabled,
            collection_period_characters_period_enabled,
            competitive_season_offset_end_time,
            config_period_client_period_telemetry_period_samplerate,
            content_period_filter_period_enabled,
            content_period_maps_period_disabled,
            eog_period_wip,
            friends_period_enabled,
            game_period_umgchat_period_enabled,
            homescreen_period_featured_queues,
            homescreen_period_patchnotes_period_base_url,
            homescreen_period_promo_period_enabled,
            homescreen_period_promo_period_key,
            homescreen_period_webtile_period_base_url,
            loginqueue_period_region,
            mainmenubar_period_collections_period_enabled,
            mainmenubar_period_debug_period_enabled,
            mainmenubar_period_profile_period_enabled,
            mainmenubar_period_progression_period_enabled,
            mainmenubar_period_shootingrange_period_enabled,
            mainmenubar_period_store_period_enabled,
            match_period_details_period_delay,
            notifications_period_enabled,
            parties_period_auto_period_balance_period_enabled,
            party_period_observers_period_enabled,
            partyinvites_period_enabled,
            patchavailability_period_enabled,
            personalization_period_equip_any_level_period_enabled,
            personalization_period_use_wide_player_identity_v2,
            ping_period_update_period_interval,
            ping_period_use_game_pods_from_parties,
            platform_faulted_period_level,
            playerfeedbacktool_period_accessurl,
            playerfeedbacktool_period_locale,
            playerfeedbacktool_period_shard,
            playerfeedbacktool_period_show,
            playerfeedbacktool_period_survey_request_rate_float,
            playscreen_period_partywidget_period_enabled,
            playscreen_period_partywidget_period_matchmaking_period_maxsize,
            playscreen_period_premier_period_enabled,
            premier_period_conferences_period_fetch_period_enabled,
            premier_period_leaderboard_tab_period_enabled,
            premier_period_match_history_tab_period_enabled,
            premier_period_playscreenflow_period_enabled,
            premier_period_roster_eligibility_check_period_enabled,
            premier_period_seasons_period_activeseason_period_enabled,
            premier_period_seasons_period_fetch_period_enabled,
            queue_period_status_period_enabled,
            rchat_period_ingame_period_enabled,
            reporterfeedback_period_fetch_period_enabled,
            reporterfeedback_period_notifications_period_enabled,
            restrictions_period_v2_period_fetch_period_enabled,
            restrictions_period_v2_period_warnings_period_enabled,
            riotwarning_period_fetch_period_enabled,
            riotwarning_period_notifications_period_enabled,
            rnet_period_use_authenticated_voice,
            russia_period_voice_period_enabled,
            settings_period_livediagnostics_period_allowedplayers,
            shootingtest_period_enabled,
            skillrating_period_enabled,
            skillrating_period_in_game_period_enabled,
            skillrating_period_pre_game_period_enabled,
            social_period_panel_period_v6_period_enabled,
            socialviewcontroller_period_enabled,
            socialviewcontroller_period_v2_period_enabled,
            store_period_is_xgp_disabled,
            store_period_use_currency_inventory_models,
            store_period_use_platform_bundle_discounted_prices,
            telemetry_period_rtp_period_eventendpoint,
            telemetry_period_rtp_period_rfc190scope,
            temp_period_voice_period_allowmuting,
            tournaments_period_enabled,
            tournaments_period_pregame_period_enabled,
            vanguard_period_accessurl,
            vanguard_period_netrequired,
            voice_period_clutchmute_period_enabled,
            voice_period_clutchmute_period_prompt_period_enabled,
            voice_period_provider,
            whisper_period_enabled,
        }
    }
}
