/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1ConfigRegionGet200Response {
    /// Date in ISO 8601 format with sub-second precision
    #[serde(rename = "LastApplication")]
    pub last_application: String,
    #[serde(rename = "Collapsed")]
    pub collapsed: Box<models::V1ConfigRegionGet200ResponseCollapsed>,
}

impl V1ConfigRegionGet200Response {
    pub fn new(last_application: String, collapsed: models::V1ConfigRegionGet200ResponseCollapsed) -> V1ConfigRegionGet200Response {
        V1ConfigRegionGet200Response {
            last_application,
            collapsed: Box::new(collapsed),
        }
    }
}

