/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PartiesV1PartiesPartyIdMuctokenGet200Response {
    #[serde(rename = "Token")]
    pub token: String,
    #[serde(rename = "Room")]
    pub room: String,
}

impl PartiesV1PartiesPartyIdMuctokenGet200Response {
    pub fn new(token: String, room: String) -> PartiesV1PartiesPartyIdMuctokenGet200Response {
        PartiesV1PartiesPartyIdMuctokenGet200Response { token, room }
    }
}
