/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CoreGameV1MatchesCurrentGameMatchIdLoadoutsGet200ResponseLoadoutsInner {
    /// Character ID
    #[serde(rename = "CharacterID")]
    pub character_id: String,
    #[serde(rename = "Loadout")]
    pub loadout: Box<models::PregameV1MatchesPreGameMatchIdLoadoutsGet200ResponseLoadoutsInner>,
}

impl CoreGameV1MatchesCurrentGameMatchIdLoadoutsGet200ResponseLoadoutsInner {
    pub fn new(character_id: String, loadout: models::PregameV1MatchesPreGameMatchIdLoadoutsGet200ResponseLoadoutsInner) -> CoreGameV1MatchesCurrentGameMatchIdLoadoutsGet200ResponseLoadoutsInner {
        CoreGameV1MatchesCurrentGameMatchIdLoadoutsGet200ResponseLoadoutsInner {
            character_id,
            loadout: Box::new(loadout),
        }
    }
}

