/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PartiesV1PartiesPartyIdGet200ResponseAccessibility {}

impl PartiesV1PartiesPartyIdGet200ResponseAccessibility {
    pub fn new() -> PartiesV1PartiesPartyIdGet200ResponseAccessibility {
        PartiesV1PartiesPartyIdGet200ResponseAccessibility {}
    }
}
