/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PartiesV1PartiesPartyIdGet200ResponseMembersInnerPlayerIdentityPreferredLevelBorderId : Preferred Level Border ID
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PartiesV1PartiesPartyIdGet200ResponseMembersInnerPlayerIdentityPreferredLevelBorderId {
}

impl PartiesV1PartiesPartyIdGet200ResponseMembersInnerPlayerIdentityPreferredLevelBorderId {
    /// Preferred Level Border ID
    pub fn new(
    ) -> PartiesV1PartiesPartyIdGet200ResponseMembersInnerPlayerIdentityPreferredLevelBorderId {
        PartiesV1PartiesPartyIdGet200ResponseMembersInnerPlayerIdentityPreferredLevelBorderId {}
    }
}
