/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PartiesV1PartiesPartyIdGet200ResponseMembersInnerPlayerIdentity {
    /// Player UUID
    #[serde(rename = "Subject")]
    pub subject: String,
    /// Card ID
    #[serde(rename = "PlayerCardID")]
    pub player_card_id: String,
    /// Title ID
    #[serde(rename = "PlayerTitleID")]
    pub player_title_id: String,
    #[serde(rename = "AccountLevel")]
    pub account_level: f64,
    #[serde(rename = "PreferredLevelBorderID")]
    pub preferred_level_border_id: Box<models::PartiesV1PartiesPartyIdGet200ResponseMembersInnerPlayerIdentityPreferredLevelBorderId>,
    #[serde(rename = "Incognito")]
    pub incognito: bool,
    #[serde(rename = "HideAccountLevel")]
    pub hide_account_level: bool,
}

impl PartiesV1PartiesPartyIdGet200ResponseMembersInnerPlayerIdentity {
    pub fn new(
        subject: String,
        player_card_id: String,
        player_title_id: String,
        account_level: f64,
        preferred_level_border_id: models::PartiesV1PartiesPartyIdGet200ResponseMembersInnerPlayerIdentityPreferredLevelBorderId,
        incognito: bool,
        hide_account_level: bool,
    ) -> PartiesV1PartiesPartyIdGet200ResponseMembersInnerPlayerIdentity {
        PartiesV1PartiesPartyIdGet200ResponseMembersInnerPlayerIdentity {
            subject,
            player_card_id,
            player_title_id,
            account_level,
            preferred_level_border_id: Box::new(preferred_level_border_id),
            incognito,
            hide_account_level,
        }
    }
}
