/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PartiesV1PartiesPartyIdGet200ResponseMembersInnerPingsInner {
    #[serde(rename = "Ping")]
    pub ping: f64,
    #[serde(rename = "GamePodID")]
    pub game_pod_id: String,
}

impl PartiesV1PartiesPartyIdGet200ResponseMembersInnerPingsInner {
    pub fn new(ping: f64, game_pod_id: String) -> PartiesV1PartiesPartyIdGet200ResponseMembersInnerPingsInner {
        PartiesV1PartiesPartyIdGet200ResponseMembersInnerPingsInner {
            ping,
            game_pod_id,
        }
    }
}

