/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PartiesV1PartiesCustomgameconfigsGet200ResponseGamePodPingServiceInfoValue {
    #[serde(rename = "SecurityHash")]
    pub security_hash: f64,
    #[serde(rename = "ObfuscatedIP")]
    pub obfuscated_ip: f64,
    #[serde(rename = "PingProxyAddress")]
    pub ping_proxy_address: String,
    #[serde(rename = "PingProxyAddresses")]
    pub ping_proxy_addresses: Vec<String>,
}

impl PartiesV1PartiesCustomgameconfigsGet200ResponseGamePodPingServiceInfoValue {
    pub fn new(security_hash: f64, obfuscated_ip: f64, ping_proxy_address: String, ping_proxy_addresses: Vec<String>) -> PartiesV1PartiesCustomgameconfigsGet200ResponseGamePodPingServiceInfoValue {
        PartiesV1PartiesCustomgameconfigsGet200ResponseGamePodPingServiceInfoValue {
            security_hash,
            obfuscated_ip,
            ping_proxy_address,
            ping_proxy_addresses,
        }
    }
}

