/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PartiesV1PartiesPartyIdGet200ResponseCustomGameDataMembership {
    #[serde(rename = "teamOne", deserialize_with = "Option::deserialize")]
    pub team_one: Option<
        Vec<models::PartiesV1PartiesPartyIdGet200ResponseCustomGameDataMembershipTeamOneInner>,
    >,
    #[serde(rename = "teamTwo", deserialize_with = "Option::deserialize")]
    pub team_two: Option<
        Vec<models::PartiesV1PartiesPartyIdGet200ResponseCustomGameDataMembershipTeamOneInner>,
    >,
    #[serde(rename = "teamSpectate", deserialize_with = "Option::deserialize")]
    pub team_spectate: Option<
        Vec<models::PartiesV1PartiesPartyIdGet200ResponseCustomGameDataMembershipTeamOneInner>,
    >,
    #[serde(rename = "teamOneCoaches", deserialize_with = "Option::deserialize")]
    pub team_one_coaches: Option<
        Vec<models::PartiesV1PartiesPartyIdGet200ResponseCustomGameDataMembershipTeamOneInner>,
    >,
    #[serde(rename = "teamTwoCoaches", deserialize_with = "Option::deserialize")]
    pub team_two_coaches: Option<
        Vec<models::PartiesV1PartiesPartyIdGet200ResponseCustomGameDataMembershipTeamOneInner>,
    >,
}

impl PartiesV1PartiesPartyIdGet200ResponseCustomGameDataMembership {
    pub fn new(
        team_one: Option<
            Vec<models::PartiesV1PartiesPartyIdGet200ResponseCustomGameDataMembershipTeamOneInner>,
        >,
        team_two: Option<
            Vec<models::PartiesV1PartiesPartyIdGet200ResponseCustomGameDataMembershipTeamOneInner>,
        >,
        team_spectate: Option<
            Vec<models::PartiesV1PartiesPartyIdGet200ResponseCustomGameDataMembershipTeamOneInner>,
        >,
        team_one_coaches: Option<
            Vec<models::PartiesV1PartiesPartyIdGet200ResponseCustomGameDataMembershipTeamOneInner>,
        >,
        team_two_coaches: Option<
            Vec<models::PartiesV1PartiesPartyIdGet200ResponseCustomGameDataMembershipTeamOneInner>,
        >,
    ) -> PartiesV1PartiesPartyIdGet200ResponseCustomGameDataMembership {
        PartiesV1PartiesPartyIdGet200ResponseCustomGameDataMembership {
            team_one,
            team_two,
            team_spectate,
            team_one_coaches,
            team_two_coaches,
        }
    }
}
