/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PartiesV1PartiesPartyIdGet200ResponseCheatData {
    #[serde(rename = "GamePodOverride")]
    pub game_pod_override: String,
    #[serde(rename = "ForcePostGameProcessing")]
    pub force_post_game_processing: bool,
}

impl PartiesV1PartiesPartyIdGet200ResponseCheatData {
    pub fn new(game_pod_override: String, force_post_game_processing: bool) -> PartiesV1PartiesPartyIdGet200ResponseCheatData {
        PartiesV1PartiesPartyIdGet200ResponseCheatData {
            game_pod_override,
            force_post_game_processing,
        }
    }
}

