/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PartiesV1PartiesPartyIdGet200ResponseErrorNotification {
    #[serde(rename = "ErrorType")]
    pub error_type: String,
    #[serde(rename = "ErroredPlayers", deserialize_with = "Option::deserialize")]
    pub errored_players: Option<
        Vec<models::PartiesV1PartiesPartyIdGet200ResponseCustomGameDataMembershipTeamOneInner>,
    >,
}

impl PartiesV1PartiesPartyIdGet200ResponseErrorNotification {
    pub fn new(
        error_type: String,
        errored_players: Option<
            Vec<models::PartiesV1PartiesPartyIdGet200ResponseCustomGameDataMembershipTeamOneInner>,
        >,
    ) -> PartiesV1PartiesPartyIdGet200ResponseErrorNotification {
        PartiesV1PartiesPartyIdGet200ResponseErrorNotification {
            error_type,
            errored_players,
        }
    }
}
