/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PregameV1MatchesPreGameMatchIdLoadoutsGet200ResponseLoadoutsInnerExpressions {
    #[serde(rename = "AESSelections")]
    pub aes_selections: Vec<models::PregameV1MatchesPreGameMatchIdLoadoutsGet200ResponseLoadoutsInnerExpressionsAesSelectionsInner>,
}

impl PregameV1MatchesPreGameMatchIdLoadoutsGet200ResponseLoadoutsInnerExpressions {
    pub fn new(aes_selections: Vec<models::PregameV1MatchesPreGameMatchIdLoadoutsGet200ResponseLoadoutsInnerExpressionsAesSelectionsInner>) -> PregameV1MatchesPreGameMatchIdLoadoutsGet200ResponseLoadoutsInnerExpressions {
        PregameV1MatchesPreGameMatchIdLoadoutsGet200ResponseLoadoutsInnerExpressions {
            aes_selections,
        }
    }
}

