/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PregameV1MatchesPreGameMatchIdLoadoutsGet200ResponseLoadoutsInnerExpressionsAesSelectionsInner {
    /// UUID
    #[serde(rename = "SocketID")]
    pub socket_id: String,
    /// UUID
    #[serde(rename = "AssetID")]
    pub asset_id: String,
    /// UUID
    #[serde(rename = "TypeID")]
    pub type_id: String,
}

impl PregameV1MatchesPreGameMatchIdLoadoutsGet200ResponseLoadoutsInnerExpressionsAesSelectionsInner {
    pub fn new(socket_id: String, asset_id: String, type_id: String) -> PregameV1MatchesPreGameMatchIdLoadoutsGet200ResponseLoadoutsInnerExpressionsAesSelectionsInner {
        PregameV1MatchesPreGameMatchIdLoadoutsGet200ResponseLoadoutsInnerExpressionsAesSelectionsInner {
            socket_id,
            asset_id,
            type_id,
        }
    }
}

