/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PregameV1MatchesPreGameMatchIdLoadoutsGet200ResponseLoadoutsInnerItemsValueSocketsValueItem {
    /// Item ID
    #[serde(rename = "ID")]
    pub id: String,
    /// Item Type ID
    #[serde(rename = "TypeID")]
    pub type_id: String,
}

impl PregameV1MatchesPreGameMatchIdLoadoutsGet200ResponseLoadoutsInnerItemsValueSocketsValueItem {
    pub fn new(id: String, type_id: String) -> PregameV1MatchesPreGameMatchIdLoadoutsGet200ResponseLoadoutsInnerItemsValueSocketsValueItem {
        PregameV1MatchesPreGameMatchIdLoadoutsGet200ResponseLoadoutsInnerItemsValueSocketsValueItem {
            id,
            type_id,
        }
    }
}

