/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PregameV1MatchesPreGameMatchIdLoadoutsGet200ResponseLoadoutsInnerItemsValueSocketsValue {
    /// UUID
    #[serde(rename = "ID")]
    pub id: String,
    #[serde(rename = "Item")]
    pub item: Box<models::PregameV1MatchesPreGameMatchIdLoadoutsGet200ResponseLoadoutsInnerItemsValueSocketsValueItem>,
}

impl PregameV1MatchesPreGameMatchIdLoadoutsGet200ResponseLoadoutsInnerItemsValueSocketsValue {
    pub fn new(id: String, item: models::PregameV1MatchesPreGameMatchIdLoadoutsGet200ResponseLoadoutsInnerItemsValueSocketsValueItem) -> PregameV1MatchesPreGameMatchIdLoadoutsGet200ResponseLoadoutsInnerItemsValueSocketsValue {
        PregameV1MatchesPreGameMatchIdLoadoutsGet200ResponseLoadoutsInnerItemsValueSocketsValue {
            id,
            item: Box::new(item),
        }
    }
}

