/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PregameV1MatchesPreGameMatchIdGet200ResponseTeamsInnerTeamId {
}

impl PregameV1MatchesPreGameMatchIdGet200ResponseTeamsInnerTeamId {
    pub fn new() -> PregameV1MatchesPreGameMatchIdGet200ResponseTeamsInnerTeamId {
        PregameV1MatchesPreGameMatchIdGet200ResponseTeamsInnerTeamId {
        }
    }
}

