/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PregameV1MatchesPreGameMatchIdLoadoutsGet200Response {
    #[serde(rename = "Loadouts")]
    pub loadouts: Vec<models::PregameV1MatchesPreGameMatchIdLoadoutsGet200ResponseLoadoutsInner>,
    #[serde(rename = "LoadoutsValid")]
    pub loadouts_valid: bool,
}

impl PregameV1MatchesPreGameMatchIdLoadoutsGet200Response {
    pub fn new(
        loadouts: Vec<models::PregameV1MatchesPreGameMatchIdLoadoutsGet200ResponseLoadoutsInner>,
        loadouts_valid: bool,
    ) -> PregameV1MatchesPreGameMatchIdLoadoutsGet200Response {
        PregameV1MatchesPreGameMatchIdLoadoutsGet200Response {
            loadouts,
            loadouts_valid,
        }
    }
}
