/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PregameV1MatchesPreGameMatchIdGet200ResponseQueueId : Queue ID
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PregameV1MatchesPreGameMatchIdGet200ResponseQueueId {}

impl PregameV1MatchesPreGameMatchIdGet200ResponseQueueId {
    /// Queue ID
    pub fn new() -> PregameV1MatchesPreGameMatchIdGet200ResponseQueueId {
        PregameV1MatchesPreGameMatchIdGet200ResponseQueueId {}
    }
}
