/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PregameV1MatchesPreGameMatchIdLoadoutsGet200ResponseLoadoutsInnerSprays {
    #[serde(rename = "SpraySelections")]
    pub spray_selections: Vec<models::PregameV1MatchesPreGameMatchIdLoadoutsGet200ResponseLoadoutsInnerSpraysSpraySelectionsInner>,
}

impl PregameV1MatchesPreGameMatchIdLoadoutsGet200ResponseLoadoutsInnerSprays {
    pub fn new(
        spray_selections: Vec<models::PregameV1MatchesPreGameMatchIdLoadoutsGet200ResponseLoadoutsInnerSpraysSpraySelectionsInner>,
    ) -> PregameV1MatchesPreGameMatchIdLoadoutsGet200ResponseLoadoutsInnerSprays {
        PregameV1MatchesPreGameMatchIdLoadoutsGet200ResponseLoadoutsInnerSprays { spray_selections }
    }
}
