/*
 * Valorant API
 *
 * Valorant API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PregameV1MatchesPreGameMatchIdLoadoutsGet200ResponseLoadoutsInner {
    /// Player UUID
    #[serde(rename = "Subject")]
    pub subject: String,
    #[serde(rename = "Sprays")]
    pub sprays: Box<models::PregameV1MatchesPreGameMatchIdLoadoutsGet200ResponseLoadoutsInnerSprays>,
    #[serde(rename = "Expressions")]
    pub expressions: Box<models::PregameV1MatchesPreGameMatchIdLoadoutsGet200ResponseLoadoutsInnerExpressions>,
    #[serde(rename = "Items")]
    pub items: std::collections::HashMap<String, models::PregameV1MatchesPreGameMatchIdLoadoutsGet200ResponseLoadoutsInnerItemsValue>,
}

impl PregameV1MatchesPreGameMatchIdLoadoutsGet200ResponseLoadoutsInner {
    pub fn new(subject: String, sprays: models::PregameV1MatchesPreGameMatchIdLoadoutsGet200ResponseLoadoutsInnerSprays, expressions: models::PregameV1MatchesPreGameMatchIdLoadoutsGet200ResponseLoadoutsInnerExpressions, items: std::collections::HashMap<String, models::PregameV1MatchesPreGameMatchIdLoadoutsGet200ResponseLoadoutsInnerItemsValue>) -> PregameV1MatchesPreGameMatchIdLoadoutsGet200ResponseLoadoutsInner {
        PregameV1MatchesPreGameMatchIdLoadoutsGet200ResponseLoadoutsInner {
            subject,
            sprays: Box::new(sprays),
            expressions: Box::new(expressions),
            items,
        }
    }
}

